### ISSUE TITLE
Rendering using HTML Canvas

### ISSUE THREAD

**Issue by wgebczyk** [ridiculousfish/shelob#1]
Hi,

First thing - really nice job! :)

Second thing, what do you think to use HTML Canvas instead of HTML Table?
I have local, crude version of render.js that seems to work.

If you would consider switching, let me know and I could create PR...

Thanks!

**Comment by ridiculousfish** [comment]
Thank you!

The reasons I avoided canvas are:

1. Text rendering typically looks worse (no subpixel antialiasing, fewer knobs to control it).
2. Difficult to do pixel-accurate drawing, especially if the canvas can be resized. For example, erasing a cell might bleed into adjacent cells.

Are there advantages? One is that the sprite drawing would be more straightforward.

**Comment by wgebczyk** [comment]
Not really to many advantages, besides way simpler code for rendering.

Thanks!
